### ISSUE TITLE
Division by 0 in dxf_input.py line 433

### ISSUE THREAD

**Issue by McNugget6750** [cnc-club/gcodetools#5]
Please check line 433 in dxf-input.py line 433

There is a division / 0 hard coded at the end. It has to be something else. 100.0 instead of 00.0 works but I'm not sure that was your intention.

**Comment by su-v** [comment]
Note that this is a bug (typo?) in the (outdated) copy of Inkscape's `dxf_input.py` module maintained in this gcodetools repository - the issue was never present in any original version of the file that was distributed with past and current Inkscape releases.

AFAICT the version of dxf_input.py in this repo is a slightly modified copy of the one distributed with Inkscape versions 0.47 to 0.48.1.

**Comment by McNugget6750** [comment]
Thank you! Checked back with InkScape and they said the same thing! Fixed and closed!
